### ISSUE TITLE
Choosing a formula Inputs

### ISSUE THREAD

**Issue by AndresF49** [FB-18-19-PreAP-CS/math-helper-EthanH44#6]
When a person is deciding which formula to choose, I feel like you should allow people to select a formula with an upper case as well as a lower case. The program only allows for lower case inputs.
For example, when deciding, I inputed 'A' rather than 'a' and you can easily allow this by adding a .lower() to your inputs.

**Comment by EthanH44** [comment]
Thank you for the input, will be adding this into code seeing how this seems pretty handy.
